### PR TITLE
Add Test Case in printable report

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by elicoidal** [comment]
:+1:

**Comment by elicoidal** [comment]
@astirpe Thanks for the contribution!
once merge, can you plan to port to 9.0?

**Review by pedrobaeza — APPROVED** [review]

**Comment by astirpe** [comment]
@elicoidal you can find the porting of this PR to the dev branch of V9 here:
https://github.com/sudhir-serpentcs/business-requirement/pull/7

**Comment by elicoidal** [comment]
@astirpe Thanks !

**Pull request merged**
