### PR TITLE
[10.0][FIX][I276] Fix the onchange function of uom

### PR DESCRIPTION
**Pull request by JoJoJoJoJoJoJo**
Ref #276 

@elicoidal @seb-elico @victormartinelicocorp @lonelysun

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM

**Comment by elicoidal** [comment]
@seb-elico @victormartinelicocorp please have a look

**Review by seb-elico — APPROVED** [review]
Code looks ok, to be tested on Runbot before merging the PR

**Comment by elicoidal** [comment]
Functional test is OK

**Pull request merged**
