### PR TITLE
[MIG]Migrated Business Requirement Deliverable Resource Template Categ from 8.0 to 10.0.

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
Issue #48 
- This PR is depend on #233 , #236 
- Migrated Business Requirement Deliverable from v8 to v10.

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
@seb-elico @victormartinelicocorp

**Comment by martintorresvm** [comment]
> This PR is depend on #233 , #236
Migrated Business Requirement Deliverable from v8 to 

@elicoidal let's wait IMO and then rebase this one

**Review by seb-elico — APPROVED** [review]

**Comment by elicoidal** [comment]
Let's wait for the rebase and functional tests

**Review by seb-elico — APPROVED** [review]
LGTM

**Review by martintorresvm — APPROVED** [review]

**Comment by elicoidal** [comment]
Waiting for dependencies to be merged and functional tests

**Comment by elicoidal** [comment]
@sudhir-serpentcs @YogeshMahera-SerpentCS you might want to rebase since #231 is now merged.
Let me know so that I can move forward

**Comment by martintorresvm** [comment]
@YogeshMahera-SerpentCS Please rebase this PR `business_requirement_deliverable_project_task_categ` unmet dependency.

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS can you rebase?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal @victormartinelicocorp  Could you please review

**Comment by martintorresvm** [comment]
@YogeshMahera-SerpentCS Did you just rebase, right? So still valid my review.

@elicoidal Can we move forward?

**Comment by elicoidal** [comment]
All good!

**Pull request merged**
