### PR TITLE
[WIP] business_requirement_deliverable_report

### PR DESCRIPTION
**Pull request by martintorresvm**
- Add some of the features of V9 branch within reports

### CODE REVIEW

**Comment by martintorresvm** [comment]
@elicoidal still WIP but if you could have a test on Runbot. The others files differs too much so it will take more time to analyze what is important to add

**Comment by elicoidal** [comment]
@victormartinelicocorp no runbot no travis. So I will wait until you can fix some :)

**Comment by elicoidal** [comment]
@victormartinelicocorp any news?

**Comment by martintorresvm** [comment]
@elicoidal Think I could give OS team this. I have no time enough and I think better focus on issues. This is more an improvement than an issue.

I'll ask them if could do it

**Comment by elicoidal** [comment]
Merging as this is essential for Travis

**Pull request merged**
