### PR TITLE
[IMP] business_requirement_etherpad

### PR DESCRIPTION
**Pull request by martintorresvm**
- Hide label as redundant

### CODE REVIEW

**Comment by martintorresvm** [comment]
Regards #244 @elicoidal

**Comment by elicoidal** [comment]
can you check as well why there is an error: 
Error

Pad creation failed, either there is a problem with your pad server URL or with your connection. 

Set up is in the company and seems incorrect. Check the newest module

**Comment by elicoidal** [comment]
linked to #239

**Comment by martintorresvm** [comment]
> can you check as well why there is an error:
Error
Pad creation failed, either there is a problem with your pad server URL or with your connection.
Set up is in the company and seems incorrect. Check the newest module

@elicoidal Actually don't have much time to work on this, @YogeshMahera-SerpentCS could help with this?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Yes, sure I am going to check that issue.
@victormartinelicocorp

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
In Company form:- pad Server url is wrong that's why you are facing Pad creation failed.
In v8 it's populated BY https://pad.openerp.com.
So you have to change it to:  https://pad.odoo.com
Then you can connect it.

brpad2
brpad1
@victormartinelicocorp

**Comment by elicoidal** [comment]
OK: @YogeshMahera-SerpentCS please modify the default set up of the module and we are good to go!

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Could you please review it.

**Review by elicoidal — APPROVED** [review]
Functional OK

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb

**Comment by elicoidal** [comment]
@seb-elico

**Comment by martintorresvm** [comment]
@elicoidal Own PR so I could not approve with the button. LGTM

**Comment by elicoidal** [comment]
#224 and #223 are merged: please rebase

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
I think this PR is not depending on #224 and #223, and this PR for v8.

**Comment by elicoidal** [comment]
you are right!

**Pull request merged**
