### PR TITLE
[9.0] Fix transifex Secure

### PR DESCRIPTION
**Pull request by elicoidal**
Following comment on https://github.com/OCA/business-requirement/issues/22#issuecomment-254262645

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please don't include names in commit, or we will be mentioned each time the branch is forked.

**Comment by elicoidal** [comment]
@pedrobaeza ouch!
Can I fix it?
 




------------------
--
 	    Eric Caudal [Founder and CEO]
                              Skype: elico.corp. Phone: + 86 186 2136 1670 (Cell), + 86 21 6211 8017/27/37 (Office)             
             Elico Shanghai (Hong Kong/Shenzhen/Singapore)             
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016
 

 
 
 
------------------ Original ------------------
From: "Pedro M. Baeza"; 
Date: 2017年2月24日(星期五) 下午4:37
To: "OCA/business-requirement"; 
Cc: "Eric @ Elico Corp"; "Author"; 
Subject: Re: [OCA/business-requirement] [9.0] Fix transifex Secure (#70)

 

Please don't include names in commit, or we will be mentioned each time the branch is forked.

**Comment by pedrobaeza** [comment]
You can amend the commit and remove that message, and the push force:
```
git commit --amend
[change message]
git push -f
```

**Review by andhit-r — APPROVED** [review]
:+1:

**Comment by elicoidal** [comment]
lol

Last time I tried something like that I broke the repo...

I will have a look

**Pull request merged**
