### PR TITLE
[8.0][FIX] business_requirement_deliverable_cost: fixes error during adding reso…

### PR DESCRIPTION
**Pull request by yustas147**
During resource line addition to business requirement the error appears:

  File ".../share/Odoo/addons/8.0/business_requirement_deliverable_cost/models/business.py", line 52, in _get_partner
    if br_deliverable.business_requirement_id.id:
AttributeError: 'bool' object has no attribute 'business_requirement_id'

### CODE REVIEW

**Comment by astirpe** [comment]
If the CLA is not signed, this fix (that is needed) cannot be merged. How to unlock this issue?

**Comment by elicoidal** [comment]
@yustas147 download the CLA document (http://odoo-community.org/page/website.cla), sign it, scan it and send it to cla@odoo-community.org, including your login password.
then we will be able to review and merge.

**Comment by elicoidal** [comment]
@yustas147 any news on the CLA?

**Comment by yustas147** [comment]
Hi Eric!

planning on monday

**Comment by elicoidal** [comment]
Great!

**Comment by yustas147** [comment]
Hello, Eric!

Could you please give me an example of correct filled ICLA scan?

Thank you!

**Comment by elicoidal** [comment]
sure: https://github.com/OCA/odoo-community.org/raw/master/ICLA.pdf
Nothing special: your name+ Address+github account in the You space and we will fill the rest!

**Comment by yustas147** [comment]
Hi , Eric!

Here is the scan image of signed ICLA.

Have a nice day!

**Comment by elicoidal** [comment]
@yustas147 I could not receive in the github the CLA. Would you mind send it to cla@odoo-community.org

**Comment by elicoidal** [comment]
@yustas147 in the meantime, can you resolve the conflicts so that we can move forward?

**Comment by yustas147** [comment]
It seems my changes are obsolete, closing this pull request.

**Pull request closed without merging**
