### PR TITLE
[FIX][business_requirement_deliverable_project] Issue #273 about UoM in task creation

### PR DESCRIPTION
**Pull request by XXXXLM**

### CODE REVIEW

**Comment by XXXXLM** [comment]
@elicoidal Please test it.

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@victormartinelicocorp

**Comment by elicoidal** [comment]
Functional tests OK

**Review by martintorresvm — APPROVED** [review]
LGTM. 

@Miya609 Just a bit surprised the UT is not failing as you changed the function.

cc @elicoidal

**Pull request merged**
