### PR TITLE
[FIX][business_requirement_deliverable] don't change deliverable description if previously filled

### PR DESCRIPTION
**Pull request by rubencabrera**
As described in #127

### CODE REVIEW

**Comment by elicoidal** [comment]
@rubencabrera 
The magic of Travis! Can you please fix the test please?
Once done I will merge your contribution
Thanks a lot!

**Comment by serpentcs-dev1** [comment]
@rubencabrera Then the same logic should be also applied [here,](https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable/models/business.py#L81) right?

**Comment by serpentcs-dev1** [comment]
dlv new
But actually IMHO this code will work only once, onchange on description will not work if it is already set so then even if you change the product again the description would remain same.

edit : So travis is also failing for this reason.

**Comment by martintorresvm** [comment]
> edit : So travis is also failing for this reason.

@darshan-serpent IMO is not the reason

Here we have the error on Travis and is true.
```
2017-05-06 10:22:52,006 5599 INFO openerp_test openerp.modules.loading: loading business_requirement_deliverable_cost/views/business.xml

2017-05-06 10:22:52,082 5599 
ERROR openerp_test openerp.addons.base.ir.ir_ui_view: 
Element '<xpath expr="//field[@name='unit_price']">' 
cannot be located in parent view

Error context:

View `business.requirement.deliverable.pivot`

[view_id: 861, xml_id: n/a, model: business.requirement.deliverable, parent_id: 853]
```
And here is the view inherited
```
        <!-- Pivot view Requirement Resources Line-->
        <record id="view_business_requirement_resource_pivot" model="ir.ui.view">
             <field name="name">business.requirement.resource.pivot</field>
             <field name="model">business.requirement.resource</field>
             <field name="arch" type="xml">
                 <graph string="Requirement Resources" type="pivot" stacked="True">
                     <field name="business_requirement_id" type="row"/>
                     <field name="business_requirement_deliverable_id" type="col"/>
                     <field name="qty" type="measure"/>
                 </graph>
             </field>
       </record>
```
I'll approve the changes.

**Review by martintorresvm — APPROVED** [review]

**Comment by elicoidal** [comment]
@darshan-serpent 
> But actually IMHO this code will work only once, onchange on description will not work if it is already set so then even if you change the product again the description would remain same.

That is the intended behavior: having the description kept even if we change the product in the deliverable.
If the user wants to get the description of the product, he/she will have to empty first the description field.

> Then the same logic should be also applied here, right?

:+1: well spotted!

**Comment by rubencabrera** [comment]
Sorry, been AFK for a few days. 
It is very annoying to change just one line of code and have to fix someone else's code, on a totally unrelated part, to make travis pass.
Any ideas if this error from the view can be fixed with a rebase or is it just a mistake that popped out now?

**Comment by serpentcs-dev1** [comment]
@rubencabrera I guess you need to rebase first, though the travis would fail from [here](https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable/tests/test_br.py#L247) as you know because the onchange will not populate the name field until it is empty.

**Comment by serpentcs-dev1** [comment]
We fixed the travis issue from [here](https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable/tests/test_br.py#L211) by changing it to : 
`            line.write({'product_id': self.productA.id, 'name': ''})
`

**Comment by martintorresvm** [comment]
> Sorry, been AFK for a few days.
It is very annoying to change just one line of code and have to fix someone else's code, on a totally unrelated part, to make travis pass.
Any ideas if this error from the view can be fixed with a rebase or is it just a mistake that popped out now?

@rubencabrera Indeed is it.

Could you rebase this PR and check if Travis passed this time?

**Comment by rubencabrera** [comment]
Rebased and there's nothing to update. Tried @darshan-serpent's suggestion for travis fix.

**Comment by serpentcs-dev1** [comment]
@rubencabrera Please check the above link that I have shared the line you have made the change is not in the expected method.

**Comment by rubencabrera** [comment]
Thank you @darshan-serpent , I guess I also did something wrong with the rebase, because when rebasing from 8.0 it said nothing to update, but my line 211 was the one I changed on the previous wrong commit. Sorry for the inconvenience.

**Comment by elicoidal** [comment]
Is this ready to merge?
@rubencabrera

**Comment by rubencabrera** [comment]
I screwed the rebase, let me tidy this mess a little bit

**Comment by serpentcs-dev1** [comment]
@rubencabrera  Yeah, I think your branch has diverged, maybe you need to reset to OCA and then commit it again :)

**Comment by rubencabrera** [comment]
Rebased done, sorry for the delay.

**Comment by elicoidal** [comment]
Thanks Ruben, I fixed as well line 81.
Merging

**Comment by elicoidal** [comment]
Travis is unrelated. Fast tracking this one

**Pull request merged**
