### PR TITLE
[13.0][MIG] business_requirement_deliverable: Migration to 13.0

### PR DESCRIPTION
**Pull request by Tardo**
Depends #332 

cc @tecnativa TT19718

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can rebase this

**Comment by Tardo** [comment]
rebased, ready to review

**Comment by pedrobaeza** [comment]
Red Travis

**Comment by Tardo** [comment]
Now green

**Comment by Tardo** [comment]
Changes done, green.

**Comment by Tardo** [comment]
This PR need reviews

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this for continuing in the dependency chain

/ocabot merge nobump

**Pull request merged**
