### PR TITLE
[8.0][IMP] Add followers of master project to BR

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
[IMP] [business_requirement] followers of master project to BR

This PR will help to add the followers of the master project to its corresponding BR.

@elicoidal @sudhir-serpentcs 

cc @darshan-serpent

Refers to issue : https://github.com/OCA/business-requirement/issues/90

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
Please check travis

**Comment by elicoidal** [comment]
once done please froward port to v9

**Comment by elicoidal** [comment]
@darshan-serpent any feedback here?

**Comment by sudhir-serpentcs** [comment]
elicoidal commented 20 hours ago
     @darshan-serpent any feedback here?
@elicoidal We are adding UT to fix travis.

**Comment by serpentcs-dev1** [comment]
Fixed Travis

@elicoidal 
cc @sudhir-serpentcs

**Comment by elicoidal** [comment]
@pedrobaeza @dreispt I think this one is good to go

**Review by dreispt — APPROVED** [review]

**Pull request merged**
