### PR TITLE
[10.0]-[MIG]-Migrated business_requirement_earned_value from v8 to v10

### PR DESCRIPTION
**Pull request by YogeshMahera-SerpentCS**
#48 

- Migrated business_requirement_earned_value from v8 to v10.

### CODE REVIEW

**Comment by elicoidal** [comment]
@seb-elico do we need this one or are you going to take care of it?
Anyway, #224 and #223 are merged: please rebase

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
rebased.

**Comment by elicoidal** [comment]
@seb-elico

**Comment by elicoidal** [comment]
This one will be rewritten

**Pull request closed without merging**
