### PR TITLE
[15.0] [MIG] business_requirement

### PR DESCRIPTION
**Pull request by MosabWadea**

### CODE REVIEW

**Comment by MosabWadea** [comment]
hello @pedrobaeza  @victoralmau can you please review this PR as I have the other modules ready for pr but this one has to be merged first

Many thanks

**Comment by MosabWadea** [comment]
hello @astirpe I can see that you contributed before to this repo, can you review this mig pr for me please, I did migrate all other BR modules and want to merge them. 

Thanks

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by Hazmi0a — APPROVED** [review]

**Pull request merged**
