### PR TITLE
[10.0][FIX] Error when generating project

### PR DESCRIPTION
**Pull request by JoJoJoJoJoJoJo**
Fix the error when generating project.
@elicoidal  @seb-elico @victormartinelicocorp @lonelysun

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb-elico

**Review by martintorresvm — APPROVED** [review]
LGTM

**Review by seb-elico — APPROVED** [review]
LGTM, to be tested on Runbot

**Comment by elicoidal** [comment]
tests OK

**Pull request merged**
