### PR TITLE
[8.0][FIX] Sales estimation ACL mismatch (Issue #91)

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
Fixed the ACL for Sales Estimation Group.

@elicoidal @sudhir-serpentcs

cc @YogeshMahera-SerpentCS

Refers to issue: https://github.com/OCA/business-requirement/issues/91

### CODE REVIEW

**Review by elicoidal — CHANGES_REQUESTED** [review]
I cannot agree to this PR as is.
It is fixing the ACL issue but contains as well the content of PR #86.
Please fix in this PR only the ACL mismatch between the  modules.
Once done and merge you will have to rebase the other PR and fix the ACL in the other PR.
Thanks!

**Comment by elicoidal** [comment]
once done, please fix v9 as well

**Comment by sudhir-serpentcs** [comment]
I will close this PR and send the new PR that will have only related code.
CC: @elicoidal

**Comment by elicoidal** [comment]
@sudhir-serpentcs could you restart this bugfix?

**Comment by serpentcs-dev1** [comment]
@elicoidal Sure, we will create a new PR for this.

**Pull request closed without merging**
