### PR TITLE
[FIX] Fixed deliverable issues

### LINKED ISSUE #125: [8.0] business_requirement_deliverable need to be consisten when DL and RL are related
Because now RL and DL could be independent but if they are related between then should belong to same BR.
1) FIX

On the Resource Lines Form and Tree view should be not possible edit business_requirement_id

If business_requirement_deliverable_id is set

Add domain on Views to fix

readonly="{'business_requirement_deliverable_id', '!=', False}

2) FIX

On the Form Deliverable

if the business_requirement_id is edit then

should be updated the business_requirement_id on the related Resource Lines

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
@victormartinelicocorp Fixes #125 
Please review.

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]

**Review by martintorresvm — APPROVED** [review]

**Comment by martintorresvm** [comment]
``` 
    @api.multi
    @api.onchange('business_requirement_id')
    def business_requirement_id_change(self):
        for deliverables in self:
            if deliverables.business_requirement_id:
                for resource in deliverables.resource_ids:
                    resource.business_requirement_id =\
                        deliverables.business_requirement_id
```

@darshan-serpent Please add UT for this and I think Coveralls will be ok

**Comment by serpentcs-dev1** [comment]
@victormartinelicocorp 
Improved code for UT.
Please review code.

**Comment by martintorresvm** [comment]
LGTM @elicoidal Could we move forward?

**Comment by elicoidal** [comment]
I think so

**Pull request merged**
