### PR TITLE
[IMP] [8.0-i193-BR001028-T22320] Made Task category field readonly if Type is Procurement in RL of DL form

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
This PR refers to Issue #193 
@elicoidal @victormartinelicocorp @seb-elico Please review.

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb-elico

**Comment by elicoidal** [comment]
@victormartinelicocorp

**Comment by martintorresvm** [comment]
@sudhir-serpentcs Duplicated with #200 ? 

https://github.com/OCA/business-requirement/pull/202/files#diff-eb3183e4c82327cdfa3addfa235ebfacR43

https://github.com/OCA/business-requirement/pull/200/files#diff-eb3183e4c82327cdfa3addfa235ebfacR12

**Comment by elicoidal** [comment]
@sudhir-serpentcs what about https://github.com/OCA/business-requirement/pull/202#issuecomment-315006725

**Comment by sudhir-serpentcs** [comment]
> @sudhir-serpentcs Duplicated with #200 ?
https://github.com/OCA/business-requirement/pull/202/files#diff-eb3183e4c82327cdfa3addfa235ebfacR43
https://github.com/OCA/business-requirement/pull/200/files#diff-eb3183e4c82327cdfa3addfa235ebfacR12

@victormartinelicocorp @elicoidal This is not duplicated with #200  as both attrs are added in different views. One is in internal tree view and another one is in main tree view.

**Comment by elicoidal** [comment]
OK: merging for trivial

**Pull request merged**
