### PR TITLE
[FIX] Master project overwritten with generated project

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
@elicoidal @seb-elico I have removed one2many reference field reference while project create.

Can you please review?

cc @sudhir-serpentcs

### CODE REVIEW

**Comment by martintorresvm** [comment]
@darshan-serpent PR duplicated https://github.com/OCA/business-requirement/pull/97/files

cc @elicoidal @seb-elico

**Comment by elicoidal** [comment]
@victormartinelicocorp shall we close this one?

**Comment by martintorresvm** [comment]
> @victormartinelicocorp shall we close this one?

@elicoidal Yes, better just have one. No problem if decide close my PR instead of @darshan-serpent one

**Comment by serpentcs-dev1** [comment]
I'm closing this one.

**Pull request closed without merging**
