### PR TITLE
[MIG][16.0] business_requirement_crm: Migration to version 16.0

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]
Ok

**Comment by AntoniRomera** [comment]
@Christian-RB Review?

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by FernandoRomera — APPROVED** [review]
LGTM

**Comment by AntoniRomera** [comment]
@pedrobaeza Can you merge, please?

**Pull request merged**
