### PR TITLE
[10.0]-[MIG]-Migrated Business requirement deliverable project from v8 to 10

### PR DESCRIPTION
**Pull request by YogeshMahera-SerpentCS**
#48 

- [MIG]Migrated Business requirement deliverable project from v8 to 10

### CODE REVIEW

**Comment by elicoidal** [comment]
Please make sure to set this module as Apps (https://github.com/OCA/business-requirement/pull/223#issuecomment-318510258)

**Comment by elicoidal** [comment]
#224 and #223 are merged: please rebase

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS please check travis

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS please check travis

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS Can you give Travis some love?

**Comment by elicoidal** [comment]
The PR needs rebase (due to the etherpad module)

**Comment by elicoidal** [comment]
First test: fields Projects is incorrect (it should not appear and there is no linked project where there should be)
screenshot from 2017-09-18 14-31-00

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Really sorry, I just missed this one.

Looking on it now.

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
Can you please review it.

**Comment by elicoidal** [comment]
- [ ] Wizard create project: can you have 2 columns for the title of the fields?
- [ ] When go to BR00002, no button available (there should be as BR0004 child is not yet generated)
- [x] BR00002/3/4 should have master project =  "ERP improvements" and BR0001 -> "Corporate Website"
- [ ] "ERP improvement" project is duplicated (probably fixed in #229).

**Comment by elicoidal** [comment]
when creating project in BR00004 (I assign to a project in the wizard and change no other option):

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/business-requirement/business_requirement_deliverable_project/wizard/generate_projects.py", line 78, in apply
    parent_project, br, project_ids, task_ids)
  File "/home/odoo/build/OCA/business-requirement/business_requirement_deliverable_project/wizard/generate_projects.py", line 116, in generate_br_projects
    br_project = project_obj.create(br_project_val)
  File "/home/odoo/odoo-10.0/addons/project/models/project.py", line 254, in create
    return super(Project, self).create(vals)
  File "/home/odoo/odoo-10.0/addons/mail/models/mail_alias.py", line 223, in create
    )).create(vals)
  File "/home/odoo/odoo-10.0/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/.repo_requirements/odoo/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/.repo_requirements/odoo/odoo/models.py", line 3983, in _create
    field.write(self.with_context(rel_context), vals[name])
  File "/.repo_requirements/odoo/odoo/fields.py", line 2172, in write
    if act[0] == 0:
TypeError: 'int' object has no attribute '__getitem__'

**Comment by elicoidal** [comment]
Currently no way to create the projects

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
> "ERP improvement" project is duplicated (probably fixed in #229).

Yes, this point covered in PR #229 .
remain points can you please check it.

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Let me know if any issue in this PR

**Comment by elicoidal** [comment]
I dont know why but I cannot rebuild the runbot. I will try later

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS 
the rule for the button Generate Project for children project should follow #205 : 
- if current BR is in SOA status and project is not generated: button should be displayed
- If any child BR is in SOA status and at least one project is not generated, display the button

Currently the behavior is not correct for BR0004 (child of BR00002) which is in SOA and project is not generated:
- Button is displayed in child BR00004 (this is correct)
- Button is not displayed in parent BR00002 (this is not correct)

if I click the button in parent BR (in SOA), the rule is: generate the project of the BR and any child BR which is in SOA status and for which the project is not yet generated.

Let me know if still unclear

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS When clicking on the parent BR button I currently cannot generate project "There is no available business requirement resource line to generate task". 
Expected: I should be able to generate the project of current valid BR and all valid children from the parent BR

**Comment by elicoidal** [comment]
- [ ] It seems that the parenting has not been set up via the OCA module as discussed (via: https://github.com/OCA/account-analytic/tree/10.0/account_analytic_parent )

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Please check this PR

**Comment by martintorresvm** [comment]
>  It seems that the parenting has not been set up via the OCA module as discussed (via: https://github.com/OCA/account-analytic/tree/10.0/account_analytic_parent )

@YogeshMahera-SerpentCS 
1) Rebase this PR
2) Add dependency: account_analytic_parent

cc @elicoidal

**Comment by YogeshMahera-SerpentCS** [comment]
@victormartinelicocorp Added account_analytic_parent as depends module and reabased PR

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS Wizard in parent still not effective
- [ ] After I generate the projects in BR00002 (Parent), If I click again, just after, I should not be able to see the wizard but currently I do. Expected: message saying that there is no resource lines to generate project
- [ ] After I generate the projects in BR00002 (Parent) for the first sub-BR000004, I set the second one BR00003 to SOA and launch the wizard in parent. Current: project is not generated for BR00003 as expected
- [ ] Parent field not created in project (along with search field and group by for parent in project tree/kanban view). Parent field should be synchronized with AA field as in v8. When wizard is launched, parent field in project should be populated by the wizard following BR structure (same as v8)

cc @sudhir-serpentcs can you help here for the parenting?

**Comment by YogeshMahera-SerpentCS** [comment]
Yes I have checked this issue in local need to discuss with @sudhir-serpentcs 
I am working on it Soon I will complete it.

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal please review it

**Comment by elicoidal** [comment]
- [ ] Generating the project in BR002: the project from BR0004 is linked to BR002 (should be BR0004)

**Comment by elicoidal** [comment]
- [ ] when setting BR0003 as SOA after the generation of Project in BR002/004: the button to generate project does not appear (expected: I should be able to generate project for BR0003)

**Comment by elicoidal** [comment]
- [ ] I still dont see any parenting field in project
@YogeshMahera-SerpentCS @sudhir-serpentcs

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal could you please check it

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal runbot is green

**Comment by elicoidal** [comment]
Still same issues as https://github.com/OCA/business-requirement/pull/231#issuecomment-333795792 and https://github.com/OCA/business-requirement/pull/231#issuecomment-333796153

**Comment by YogeshMahera-SerpentCS** [comment]
Let me quick check

**Comment by elicoidal** [comment]
No parenting either: https://github.com/OCA/business-requirement/pull/231#issuecomment-333796487

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
My Procedure steps:

BR002(SOA) is Parent and BR003 and BR004 as child

If BR0004 and BR003 are on draft stage.

From BR002 I can generate Projects for BR002 after generating project, I go to BR004, move it to SOA stage and Back to BR002 where I can see generate button and I can generate project for BR004 but here BR003 still on draft stage, so for it projects wont be generated.

then go to BR003 and move to SOA stage and generate project from BR003 then back to BR002 now I wont  be able to see generate project button as all child BR have projects created.

This is the process I follow, do you think it is right?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Parent Id Added in tree view/Kanban of project

**Comment by elicoidal** [comment]
That is correct but the project from BR4 is associated to BR2. Besides no task where generated.

**Comment by elicoidal** [comment]
and if all children are draft then the button should not generate anything (unless parent is SOA and has valid RL)

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS When I install the module in EE I have 2 unnamed smart buttons from the project module:
screenshot from 2017-10-04 07-57-16
Can you have a look at it?

FYI: I am testing manually as runbot is not really usable these days

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Improved button look

**Review by elicoidal — APPROVED** [review]
Button looks much better.
Project creation is OK.

**Comment by YogeshMahera-SerpentCS** [comment]
Thanks @elicoidal 😄

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS I see the parenting is here (in the tree you can group by) but do not see where it is defined in the project (and how to change it).
I am not sure about the field "sub-task Project" and the usage (and whether it would be useful in our need).

Other than that LGTM

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
It's base field
regarding subtask_project_id: -
Choosing a sub-tasks project will both enable sub-tasks and set their default project (possibly the project itself)

https://github.com/odoo/odoo/blob/10.0/addons/hr_timesheet/project_timesheet.py#L10

**Comment by elicoidal** [comment]
Refactoring placing the project parenting in a separate module

**Comment by YogeshMahera-SerpentCS** [comment]
Refactored and It's depends on this  [PR](https://github.com/OCA/project/pull/326)

**Comment by YogeshMahera-SerpentCS** [comment]
Fixed issue of #250 
@elicoidal

**Comment by elicoidal** [comment]
Please rebase as https://github.com/OCA/project/pull/326 is merged
@YogeshMahera-SerpentCS

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal rebased

**Comment by elicoidal** [comment]
Tested and not really yet working:
- [ ] account_analytic_parent is not installed in the runbot database (project_parent is though).
- [ ] Created projects from sub-BR should have the parent of the project linked to the parent BR.

Side note (to be added to the project_parent module in separate PR): add a smart button in the project form view to be able to list the child projects

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Yes I am checking

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Could you please review it 

>Side note (to be added to the project_parent module in separate PR): add a smart button in the project form view to be able to list the child projects

Regarding this I will make another PR - WIP

**Review by elicoidal — APPROVED** [review]
@YogeshMahera-SerpentCS 
Projects have the right parent but the analytic parent module is not loaded (due to the fact it is not in the dependencies of project_parent module: so not this PR).
I approve for this reason
cc @victormartinelicocorp @seb-elico

**Comment by elicoidal** [comment]
@victormartinelicocorp can you review so that we can merge and move forward the depending PR?

**Review by martintorresvm — APPROVED** [review]
LGTM
+ Let's move forward If functionality it's ok.
- Some functions are quite big now.
- Probably would need docstrings.

**Pull request merged**
