### PR TITLE
[ADD] business_requirement_deliverable_project_task_categ

### PR DESCRIPTION
**Pull request by martintorresvm**
Regards https://github.com/OCA/business-requirement/issues/102
Integration Project Task generation with Project Task Category Main

### CODE REVIEW

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Please review. This module integrate Project Category Main with BRDP generation

**Review by elicoidal — APPROVED** [review]
:+1:

**Comment by elicoidal** [comment]
@dreispt @pedrobaeza

**Comment by elicoidal** [comment]
@pedrobaeza @dreispt I think this one is good to go

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
