### PR TITLE
[FIX] business_requirement_deliverable and business_requirement_deliverable_cost

### PR DESCRIPTION
**Pull request by martintorresvm**
[FIX] business_requirement_deliverable_cost
- Actual ACL configuration makes imposible for a BR user
create,modify,duplicate properly a BR with the modules:
  - business_requirement_deliverable
  - business_requirement_deliverable_cost
- Need to move the ACL restrictions on View level.

### CODE REVIEW

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Could have a look?

**Review by dreispt — APPROVED** [review]

**Review by rubencabrera — APPROVED** [review]
:+1:

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@seb-elico @dreispt @pedrobaeza 

I personally prefer the control at model level (to avoid export or ERPPeek leaks) but I do not see how to achieve reasonable usability.

Shall we override the copy function and use SUDO instead?

**Review by elicoidal — COMMENTED** [review]
@seb-elico @dreispt @pedrobaeza

I personally prefer the control at model level (to avoid export or ERPPeek leaks) but I do not see how to achieve reasonable usability.

Shall we override the copy function and use SUDO instead?

**Comment by martintorresvm** [comment]
@elicoidal To override functions is not only for the `copy` function also need to be  done for `create` and `write` and take care to rewrite the `create_uid` and `write_uid` with the original user after `sudo()`. 

About security:

IMHO a user just for have access to a production server should be considered a the main vulnerability even if the user doesn't have the rights on Odoo to read these fields by using erppeek scripts. 

Just for example if could have access to the postgres DB could hack very easy `admin` password and whatever happens is depends on the intention.

To avoid the export:

We could set of a list of fields that if exist on the `fields_to_export` from the `export_data` function then need to check if belong to these groups.

**Comment by elicoidal** [comment]
@victormartinelicocorp I understand the limit of SUDO and yes we can tweak the export data function but for ERPPeek, no need to have admin or Postgres access and there is still a risk.

**Comment by dreispt** [comment]
AFAICS the root of the problem is that you want is to limit write access on specific fields.
The problem with `groups` on a field is that it makes the field totally inaccessible to other users, so its not fit for that job.

While the current solution is a good workaround, it does not ensure actual security on those fields, as Eric pointed out.
The proper solution is to control the write on those fields at the ORM level, in the `create`/`write` methods.
That could be done on top of this PR.

**Comment by elicoidal** [comment]
OK Merging. 
Another PR will be prepare to cap the users rights on read/write and delete functions.

**Pull request merged**
