### PR TITLE
[FIX] business_requirement

### PR DESCRIPTION
**Pull request by martintorresvm**
Need to add Stakeholder Group for this State Approval.
	modified:   business_requirement/__openerp__.py
	modified:   business_requirement/security/security.xml
	modified:   business_requirement/views/business_view.xml

### CODE REVIEW

**Comment by martintorresvm** [comment]
@elicoidal Please review

**Comment by elicoidal** [comment]
:+1:

**Comment by astirpe** [comment]
:+1: 
Please don't forget to do the same for V9

**Comment by martintorresvm** [comment]
> Please don't forget to do the same for V9

Yes, thanks by the reminder.

**Review by andhit-r — APPROVED** [review]
:+1:

**Pull request merged**
