### PR TITLE
[IMP] Add internal comment for odoo users

### PR DESCRIPTION
**Pull request by martintorresvm**
cc @Tecnativa

### CODE REVIEW

**Review by Tardo — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Can you put an screenshot on how this is shown in the UI?

**Comment by pedrobaeza** [comment]
That was my suspect... Please put `nolabel="1"` in the field.

**Comment by martintorresvm** [comment]
changes done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request closed without merging**
