### PR TITLE
Update image link as they where not visible in app

### PR DESCRIPTION
**Pull request by elicoidal**
link to this issue: https://github.com/OCA/maintainer-tools/pull/221
@ pedro can we FT this one?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247262649%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247271010%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247272750%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247594434%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247598235%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/OCA/business-requirement/pull/21%23issuecomment-247262649%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20would%20like%20to%20explore%20the%20option%20of%20having%20the%202%20figure%20without%20alt%20text%20to%20see%20if%20it%27s%20rendered%20correctly%20in%20GitHub%20and%20in%20Odoo.%20Can%20you%20check%20it%3F%22%2C%20%22created_at%22%3A%20%222016-09-15T08%3A00%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pedrobaeza%20done.%5Cr%5CnGithub%20shows%20the%20link%20of%20the%20second%20invisible%20image.%5Cr%5CnTravis%20is%20broken%20for%20transifex%20and%20Runbot%20seems%20stalled...%22%2C%20%22created_at%22%3A%20%222016-09-15T08%3A43%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22Travis%20was%20broken%20before%20this%20PR.%20It%27s%20something%20in%20the%20base%20module.%20We%20can%20check%20it%20later.%22%2C%20%22created_at%22%3A%20%222016-09-15T08%3A51%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20afraid%20any%20of%20the%20combinations%20works%20on%20apps.odoo.com%2C%20so%20we%20should%20contact%20%40odony%20for%20finding%20a%20way%20to%20put%20images%20in%20RST%20or%20a%20fix%20in%20the%20apps%20platform%20itself.%22%2C%20%22created_at%22%3A%20%222016-09-16T13%3A00%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20didnot%20put%20the%20./images/...%20one%20which%20I%20think%20works.%5Cr%5CnI%20could%20try%20but%20I%20dont%20think%20that%20is%20a%20solution%20anyway%3A%20we%20should%20have%20a%20common%20compatibility%20between%20Github/apps/Odoo.%5Cr%5CnI%20will%20revert%20this%20test%22%2C%20%22created_at%22%3A%20%222016-09-16T13%3A18%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/OCA/business-requirement/pull/21#issuecomment-247262649'>General Comment</a></b>
- <a href='https://github.com/pedrobaeza'></a> I would like to explore the option of having the 2 figure without alt text to see if it's rendered correctly in GitHub and in Odoo. Can you check it?
- <a href='https://github.com/elicoidal'></a> @pedrobaeza done.
  Github shows the link of the second invisible image.
  Travis is broken for transifex and Runbot seems stalled...
- <a href='https://github.com/pedrobaeza'></a> Travis was broken before this PR. It's something in the base module. We can check it later.
- <a href='https://github.com/pedrobaeza'></a> I'm afraid any of the combinations works on apps.odoo.com, so we should contact @odony for finding a way to put images in RST or a fix in the apps platform itself.
- <a href='https://github.com/elicoidal'></a> I didnot put the ./images/... one which I think works.
  I could try but I dont think that is a solution anyway: we should have a common compatibility between Github/apps/Odoo.
  I will revert this test

<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/21?approve=1'></a>&nbsp;<a href='https://github.com/OCA/business-requirement/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dreispt** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/OCA/business-requirement/pull/21'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by pedrobaeza** [comment]
I would like to explore the option of having the 2 figure without alt text to see if it's rendered correctly in GitHub and in Odoo. Can you check it?

**Comment by elicoidal** [comment]
@pedrobaeza done.
Github shows the link of the second invisible image.
Travis is broken for transifex and Runbot seems stalled...

**Comment by pedrobaeza** [comment]
Travis was broken before this PR. It's something in the base module. We can check it later.

**Comment by pedrobaeza** [comment]
I'm afraid any of the combinations works on apps.odoo.com, so we should contact @odony for finding a way to put images in RST or a fix in the apps platform itself.

**Comment by elicoidal** [comment]
I didnot put the ./images/... one which I think works.
I could try but I dont think that is a solution anyway: we should have a common compatibility between Github/apps/Odoo.
I will revert this test

**Pull request merged**
