### PR TITLE
Update README to correct runbot address + figure

### PR DESCRIPTION
**Pull request by elicoidal**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240297383%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240576762%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240577698%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240672671%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240718395%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/OCA/business-requirement/pull/12%23issuecomment-240297383%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7480536/badge%29%5D%28https%3A//coveralls.io/builds/7480536%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2090.431%25%20when%20pulling%20%2A%2A95fa46fb710f0dc7ee8dec9763e870608147aeb3%20on%208.0-br-readme%2A%2A%20into%20%2A%2A843f43882a9641f9b63988b1d9099b1ec51c47f6%20on%208.0%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T02%3A31%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pedrobaeza%20%40dreispt%20we%20can%20move%20on%22%2C%20%22created_at%22%3A%20%222016-08-17T23%3A09%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7497612/badge%29%5D%28https%3A//coveralls.io/builds/7497612%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2090.431%25%20when%20pulling%20%2A%2Afb8843f05ff69f61cb248552db20eaa60c83eb68%20on%208.0-br-readme%2A%2A%20into%20%2A%2A843f43882a9641f9b63988b1d9099b1ec51c47f6%20on%208.0%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T23%3A14%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-18T09%3A34%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22%2B1%22%2C%20%22created_at%22%3A%20%222016-08-18T13%3A12%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6644187%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/moylop260%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/OCA/business-requirement/pull/12#issuecomment-240297383'>General Comment</a></b>
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/7480536)
  Coverage remained the same at 90.431% when pulling **95fa46fb710f0dc7ee8dec9763e870608147aeb3 on 8.0-br-readme** into **843f43882a9641f9b63988b1d9099b1ec51c47f6 on 8.0**.
- <a href='https://github.com/elicoidal'></a> @pedrobaeza @dreispt we can move on
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/7497612)
  Coverage remained the same at 90.431% when pulling **fb8843f05ff69f61cb248552db20eaa60c83eb68 on 8.0-br-readme** into **843f43882a9641f9b63988b1d9099b1ec51c47f6 on 8.0**.
- <a href='https://github.com/pedrobaeza'></a> :+1:
- <a href='https://github.com/moylop260'></a> +1

<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/12?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/12?approve=1'></a>&nbsp;<a href='https://github.com/OCA/business-requirement/pull/12'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dreispt** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/OCA/business-requirement/pull/12'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by elicoidal** [comment]
@pedrobaeza @dreispt we can move on

**Comment by pedrobaeza** [comment]
:+1:

**Comment by moylop260** [comment]
+1

**Pull request merged**
