### PR TITLE
[FIX][8.0-i181-BR001028-T22316] BR ordering on Tree view

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
@elicoidal @seb-elico @victormartinelicocorp 
#181 Fixed order on tree view.
Please review code.

### CODE REVIEW

**Comment by elicoidal** [comment]
duplicate of https://github.com/OCA/business-requirement/pull/180 and still does not work. I will close my PR.

Needs more thinking to find the reason

**Comment by sudhir-serpentcs** [comment]
@elicoidal 
removed [order](https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable_project/models/business.py#L10) field then fixed order in tree view.
Please review code.

**Review by elicoidal — APPROVED** [review]
Finally :smile:

**Comment by elicoidal** [comment]
fast tracking

**Pull request merged**
