### PR TITLE
[MIG]-Migrated Business Requirement Deliverable from 8.0 to 10.0.

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
Issue #48

- This PR is depend on #223.
- Migrated Business Requirement Deliverable from v8 to v10.

### CODE REVIEW

**Review by elicoidal — COMMENTED** [review]
LGTM.
Will wait for dependency before tests

**Comment by elicoidal** [comment]
@sudhir-serpentcs I think I have not seen the printout from #232

**Comment by elicoidal** [comment]
Please make sure to set this module as Apps (https://github.com/OCA/business-requirement/pull/223#issuecomment-318510258)

**Comment by sudhir-serpentcs** [comment]
@elicoidal , Now 'Business Requirement Deliverable' module is set as Apps.

**Comment by elicoidal** [comment]
@sudhir-serpentcs Could you please rebase as #223 is now merged?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal @victormartinelicocorp   rebased.

By mistake, I removed all commits from the branch which automatic closed PR.but now retrieved all code and it rebased :smiley:  
Could you please check it?

**Comment by elicoidal** [comment]
- [x] In runbot, some deliverable products are created 2 times (SER01, SER02, SER03)
- [x] In deliverable menu there should be pivot view (no dimension by default)
- [x] In resources menu there should be pivot view (no dimension by default)

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb-elico can you have a look?

**Comment by elicoidal** [comment]
- [x] Revenue field in Deliverable Line should be readonly

**Comment by elicoidal** [comment]
- [x] The smart button display for deliverable should not include decimals (or should use accounting dp)
screenshot from 2017-08-16 20-14-03

**Comment by sudhir-serpentcs** [comment]
@elicoidal 

> In runbot, some deliverable products are created 2 times (SER01, SER02, SER03)

I could not able to find the products which were created 2 times on runbot. It would be more helpful if you can provide the steps you followed or can provide the screenshots.

**Comment by elicoidal** [comment]
some additional issues after testing:
- [x] There is an issue for the product and demo data. For example, product SER03 Consultant is not visible in the menu BR/configuration/product (issue variant/template?). Consultant is still duplicated when selecting in the DL
- [x] In pivot table, do not add dimensions in Deliverable. To be noted that some measures are in the dimensions (quantity, sales price)
- [x] Cannot open pivot table in RL (and please remove all dimensions if any)

**Comment by elicoidal** [comment]
- [x] if a task is procurement type field "assigned to" should be R/O
- [ ] when create a new BR, the focus is on Use case field (was corrected in v8 - strange)

**Comment by elicoidal** [comment]
- [x] add a space after name and before the "-" 
- [x] in printout if the field is empty do not display (customer story/gap/use case/scenario). ONHOLD to the the html tags
- [x] My mistake: printout about the RL should be added into this module too
- [x] I am missing the kanban view for BR
- [x] graph view for BR is crashing
- [x] Pivot view for BR: remove the dimensions. Total Revenue should be available as measure
- [x] in DL/pivot view: there are 3 times dimension "Business Requirement". Adapt the name (Project and Stakeholder)
- [x] in BR / Tree view: remove Change request. Add Stakeholder (after responsible)
- [x] Everywhere (fields, filters name etc): change the name "Customer" for "Stakeholder"
- [x] In RL tree view, Filters: there is 3 times Business Requirement in the list of fields. Same in pivot view. Remove the default dimensions

**Comment by elicoidal** [comment]
@sudhir-serpentcs Let me know if unclear

**Comment by elicoidal** [comment]
@sudhir-serpentcs Any news? Main functions are still failing

**Comment by elicoidal** [comment]
@sudhir-serpentcs Any news?

**Comment by sudhir-serpentcs** [comment]
@elicoidal @victormartinelicocorp 
Some of the comments belong to `business_requirement` module so I have made new PR please review first #243 .

**Comment by elicoidal** [comment]
I have updated the feedback @sudhir-serpentcs

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS @sudhir-serpentcs is it ready for tests?
We are waiting for this to be finished in order to continue with the other PR.

**Comment by martintorresvm** [comment]
@YogeshMahera-SerpentCS @sudhir-serpentcs is it ready for tests?
We are waiting for this to be finished in order to continue with the other PR.

This is blocking others PR to pass test.

**Comment by YogeshMahera-SerpentCS** [comment]
@victormartinelicocorp @elicoidal Yes but this PR depends on #243 .
Once it merge we are ready for test.

**Comment by martintorresvm** [comment]
> when create a new BR, the focus is on Use case field (was corrected in v8 - strange)

@elicoidal Think this point better fix on other PR affecting just BR module.

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS Many things fixed.
- [x] Please remove the dimensions in all Pivot views
- [ ] Pending: use case focus
- [x] Product duplication

Can you review it?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 

> Product duplication

Moved Product demo data from BR to BRD.
So again remove Code from PR #243 and added in same PR.

>  Please remove the dimensions in all Pivot views

Removed dimensions.

**Comment by elicoidal** [comment]
BR pivot:
- [x] Total revenue as dimension...:
screenshot from 2017-09-05 19-14-39

- [x] remove default dimension to pivot for BR/BRD/BRR. They should all look like:
screenshot from 2017-09-05 19-15-44
- [ ] in resource and deliverable pivot: remove sequence as dimension
- [x] in deliverable form menu: if I type SER in deliverable product I have 3 entry of each

@YogeshMahera-SerpentCS it seems nothing has been fixed
cc @sudhir-serpentcs

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
Some of the minor improvements done.
can you please test as follows:-
BR pivot:- #243 (runbot)
BRD pivot:- Current PR runbot
BRR pivot:- Current PR runbot

> in deliverable form menu: if I type SER in deliverable product I have 3 entry of each

for that issue we have not modified BR module in this PR:-
Once #243 merge we are ready for test.

**Comment by elicoidal** [comment]
> BR pivot:- #243 (runbot)

:+1: 
> BRD pivot:- Current PR runbot
BRR pivot:- Current PR runbot

:+1: 

But sequences are still in the measures

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 

I checked the issue yes you are right:- sequences are still in measures

But I haven't added any sequence field in pivot view.

I think numeric fields(Integer, Float) will are taken as the default measure, that is what I deduced!

cc
@victormartinelicocorp @sudhir-serpentcs

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS I assume you are right: there must be a way to exclude them

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 

Yes I already searched for it if there might be any widget to exclude it.

I checked everywhere, googled it, checked in the base but there is no such default options available for hiding or remove.

**Comment by YogeshMahera-SerpentCS** [comment]
I think it is coming from the JS part, not sure though.

**Comment by elicoidal** [comment]
@dreispt @pedrobaeza @lasley  if you could give us your insight it would be wonderful:

In summary, we have a field sequence for sorting (drag'n'drop) the resource lines. This fields appears in the measure of the pivot table (because it is integer) which is not desired obviously.
It seems that there is no way to avoid this behaviour: do you confirm or would you have a suggestion where we could look at?

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS #243 is merged

**Comment by YogeshMahera-SerpentCS** [comment]
@victormartinelicocorp Now it is rebased and squashed. Now it I think it is mergeable :smile: 

Can you please review?

**Comment by martintorresvm** [comment]
> @victormartinelicocorp Now it is rebased and squashed. Now it I think it is mergeable :smile:
Can you please review?

As soon pass the test, of course

**Review by martintorresvm — APPROVED** [review]
To be tested

**Comment by YogeshMahera-SerpentCS** [comment]
@victormartinelicocorp @elicoidal 
>There is an issue for the product and demo data. For example, product SER03 Consultant is not visible in the menu BR/configuration/product (issue variant/template?). Consultant is still duplicated when selecting in the DL


peek 2017-09-11 15-59


Fixed duplicate product issue.

**Comment by elicoidal** [comment]
Hehe: something looks wrong to me... Can you find what? :stuck_out_tongue_winking_eye: 

screenshot from 2017-09-11 18-31-39

Besides can you make sure:
- [x] Add graph view to Deliverable menu

Still pending (annoying but non blocking):

- [ ] Focus is on Use Case
- [x] Sequence and level appears as measures in pivot

All the rest looks good :smile: Almost there

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 

Oops! You have a hawk eye I must admit! :smile: 

Clumsy me was testing actually! But have made the changes think now everything is clear!

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS LGTM.
for your info, I recheck and spotted the same issue in standard Odoo about the sequence in pivot (eg: tasks):
screenshot from 2017-09-12 08-47-07

So we will take it as a nice-to-have to-be-fixed bug in Odoo, hoping that in v11, the situation is better

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@seb-elico can you have a quick look so that we can move forward?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Sure, thanks for your review and test!

**Pull request merged**
