### PR TITLE
Update README to correct runbot address + figure

### PR DESCRIPTION
**Pull request by elicoidal**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240298038%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240300261%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240346526%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240347329%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240348628%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240349030%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240363079%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240367031%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240367769%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240371200%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240371321%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240372612%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240375989%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240576867%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240576915%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240672690%22%2C%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240718301%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/OCA/business-requirement/pull/13%23issuecomment-240298038%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7480567/badge%29%5D%28https%3A//coveralls.io/builds/7480567%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2090.431%25%20when%20pulling%20%2A%2A696304baf2f7d2ff954415bd9a0e813240cb7ae1%20on%208.0-brd-readme%2A%2A%20into%20%2A%2A843f43882a9641f9b63988b1d9099b1ec51c47f6%20on%208.0%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T02%3A36%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22not%20sure%20why%20the%20travis%20is%20failing%20%28Transifex%20password%29%20and%20seems%20unrelated%20%28%20%40moylop260%20%40gurneyalex%20%40dreispt%20%29%22%2C%20%22created_at%22%3A%20%222016-08-17T02%3A53%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22Transifex%20is%20not%20setup%20for%20this%20repo%2C%20and%20I%27m%20not%20sure%20about%20the%20proper%20process%20for%20that.%5Cr%5CnFor%20now%2C%20the%20Transifex%20build%20should%20be%20disabled%20from%20the%20%60.travis.yml%60.%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A26%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1246629%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dreispt%22%7D%7D%2C%20%7B%22body%22%3A%20%22You%20need%20to%20follow%20the%20instructions%20in%20the%20.travis.yml%20itself%20for%20generating%20the%20secret%3A%20https%3A//github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml%23L37-L41%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A29%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22thanks%20all%3A%20we%20will%20proceed%20with%20transifex%20setup%20in%20separate%20PR.%5Cr%5CnCan%20I%20have%20your%20approval%20for%20this%20one%20as%20this%20is%20unrelated%3F%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A35%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22But%20I%20see%20the%20preview%20and%20it%27s%20not%20working...%22%2C%20%22created_at%22%3A%20%222016-08-17T08%3A37%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-08-17T09%3A37%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1246629%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dreispt%22%7D%7D%2C%20%7B%22body%22%3A%20%22Maybe%20I%20am%20doing%20something%20wrong%20but%20I%20was%20told%20to%20include%20the%20name%20of%20the%20module%20in%20the%20path%20so%20that%20Odoo%20can%20properly%20display%20the%20rst.%5Cr%5CnWith%20the%20name%20of%20the%20module%2C%20my%20editor%20doesnot%20display%20it%20but%20it%20is%20properly%20displayed%20in%20the%20application%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T09%3A55%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22In%20this%20PR%20is%20just%20the%20opposite%3A%20https%3A//github.com/OCA/server-tools/pull/456%22%2C%20%22created_at%22%3A%20%222016-08-17T09%3A58%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pedrobaeza%20you%20are%20right%20and%20now%20I%20am%20confused...%5Cr%5CnThere%20was%20a%20discussion%20with%20%40jbeficent%20about%20the%20topic%20but%20cannot%20remember%20where.%5Cr%5Cnstandard%20rst%20is%20upper%20directory%20only%20and%20I%20was%20suggested%20to%20add%20the%20module%20name%20as%20well%20and%20indeed%20the%20module%20display%20properly%20in%20Odoo%20with%20the%20later%20option%20%28but%20not%20in%20rst/github...%29%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T10%3A14%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22Anyway%3A%20just%20let%20me%20know%20and%20I%20will%20adapt%20the%20PR%20according%20but%20now%20I%20dont%20know%20which%20rule%20to%20follow%22%2C%20%22created_at%22%3A%20%222016-08-17T10%3A15%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20correct%20seems%20to%20be%20the%20other%20way.%22%2C%20%22created_at%22%3A%20%222016-08-17T10%3A21%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%3A%20I%20will%20remove%20the%20full%20path%20and%20adapt%20the%20PR.%22%2C%20%22created_at%22%3A%20%222016-08-17T10%3A39%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7497552/badge%29%5D%28https%3A//coveralls.io/builds/7497552%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2090.431%25%20when%20pulling%20%2A%2A7b88ba10bf22cab90b506d1644be1ba4b4db57ee%20on%208.0-brd-readme%2A%2A%20into%20%2A%2A843f43882a9641f9b63988b1d9099b1ec51c47f6%20on%208.0%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T23%3A10%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pedrobaeza%20%40dreispt%20we%20can%20move%20on%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-17T23%3A10%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-08-18T09%3A34%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7165771%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pedrobaeza%22%7D%7D%2C%20%7B%22body%22%3A%20%22%2B1%22%2C%20%22created_at%22%3A%20%222016-08-18T13%3A12%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6644187%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/moylop260%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/OCA/business-requirement/pull/13#issuecomment-240298038'>General Comment</a></b>
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/7480567)
  Coverage remained the same at 90.431% when pulling **696304baf2f7d2ff954415bd9a0e813240cb7ae1 on 8.0-brd-readme** into **843f43882a9641f9b63988b1d9099b1ec51c47f6 on 8.0**.
- <a href='https://github.com/elicoidal'></a> not sure why the travis is failing (Transifex password) and seems unrelated ( @moylop260 @gurneyalex @dreispt )
- <a href='https://github.com/dreispt'></a> Transifex is not setup for this repo, and I'm not sure about the proper process for that.
  For now, the Transifex build should be disabled from the `.travis.yml`.
- <a href='https://github.com/pedrobaeza'></a> You need to follow the instructions in the .travis.yml itself for generating the secret: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L37-L41
- <a href='https://github.com/elicoidal'></a> thanks all: we will proceed with transifex setup in separate PR.
  Can I have your approval for this one as this is unrelated?
- <a href='https://github.com/pedrobaeza'></a> But I see the preview and it's not working...
- <a href='https://github.com/dreispt'></a> :+1:
- <a href='https://github.com/elicoidal'></a> Maybe I am doing something wrong but I was told to include the name of the module in the path so that Odoo can properly display the rst.
  With the name of the module, my editor doesnot display it but it is properly displayed in the application
- <a href='https://github.com/pedrobaeza'></a> In this PR is just the opposite: https://github.com/OCA/server-tools/pull/456
- <a href='https://github.com/elicoidal'></a> @pedrobaeza you are right and now I am confused...
  There was a discussion with @jbeficent about the topic but cannot remember where.
  standard rst is upper directory only and I was suggested to add the module name as well and indeed the module display properly in Odoo with the later option (but not in rst/github...)
- <a href='https://github.com/elicoidal'></a> Anyway: just let me know and I will adapt the PR according but now I dont know which rule to follow
- <a href='https://github.com/pedrobaeza'></a> The correct seems to be the other way.
- <a href='https://github.com/elicoidal'></a> OK: I will remove the full path and adapt the PR.
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/7497552)
  Coverage remained the same at 90.431% when pulling **7b88ba10bf22cab90b506d1644be1ba4b4db57ee on 8.0-brd-readme** into **843f43882a9641f9b63988b1d9099b1ec51c47f6 on 8.0**.
- <a href='https://github.com/elicoidal'></a> @pedrobaeza @dreispt we can move on
- <a href='https://github.com/pedrobaeza'></a> :+1:
- <a href='https://github.com/moylop260'></a> +1

<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/13?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/OCA/business-requirement/pull/13?approve=1'></a>&nbsp;<a href='https://github.com/OCA/business-requirement/pull/13'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dreispt** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/OCA/business-requirement/pull/13'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by elicoidal** [comment]
not sure why the travis is failing (Transifex password) and seems unrelated ( @moylop260 @gurneyalex @dreispt )

**Comment by dreispt** [comment]
Transifex is not setup for this repo, and I'm not sure about the proper process for that.
For now, the Transifex build should be disabled from the `.travis.yml`.

**Comment by pedrobaeza** [comment]
You need to follow the instructions in the .travis.yml itself for generating the secret: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L37-L41

**Comment by elicoidal** [comment]
thanks all: we will proceed with transifex setup in separate PR.
Can I have your approval for this one as this is unrelated?

**Comment by pedrobaeza** [comment]
But I see the preview and it's not working...

**Comment by dreispt** [comment]
:+1:

**Comment by elicoidal** [comment]
Maybe I am doing something wrong but I was told to include the name of the module in the path so that Odoo can properly display the rst.
With the name of the module, my editor doesnot display it but it is properly displayed in the application

**Comment by pedrobaeza** [comment]
In this PR is just the opposite: https://github.com/OCA/server-tools/pull/456

**Comment by elicoidal** [comment]
@pedrobaeza you are right and now I am confused...
There was a discussion with @jbeficent about the topic but cannot remember where.
standard rst is upper directory only and I was suggested to add the module name as well and indeed the module display properly in Odoo with the later option (but not in rst/github...)

**Comment by elicoidal** [comment]
Anyway: just let me know and I will adapt the PR according but now I dont know which rule to follow

**Comment by pedrobaeza** [comment]
The correct seems to be the other way.

**Comment by elicoidal** [comment]
OK: I will remove the full path and adapt the PR.

**Comment by elicoidal** [comment]
@pedrobaeza @dreispt we can move on

**Comment by pedrobaeza** [comment]
:+1:

**Comment by moylop260** [comment]
+1

**Pull request merged**
