### PR TITLE
[FIX][8.0] Fix issue with demo data on DB without demo data

### PR DESCRIPTION
**Pull request by seb-elico**
1. Add `forcecreate="0"` to all demo data records.

Else, Odoo tries to validate the demo data file even if there's
no demo data installed in the DB, which leads to following
errors:
 - duplicate key value violates unique constraint
 - External ID not found in the system

2. Move demo data file to demo folder, following OCA guidelines.

See:
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#directories

### CODE REVIEW

**Comment by seb-elico** [comment]
@elicoidal @victormartinelicocorp

**Comment by seb-elico** [comment]
@pedrobaeza 

What's your feeling about the `forcecreate="0"`? I'm quite surprised that this is what solved our issue when upgrading the BR modules.

This is the following message from Nathan Beck that led me to this solution:
https://www.odoo.com/forum/help-1/question/data-noupdate-0-1-in-security-xml-13546

FYI, some of the stacktraces we had when updating the modules:

````
2017-09-12 05:17:30,744 351 ERROR XXX openerp.sql_db: bad query: INSERT INTO "business_requirement_category" ("id", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('business_requirement_category_id_seq'), 'ERP', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "business_requirement_category_pkey"
DETAIL:  Key (id)=(55) already exists.

2017-09-12 05:17:30,747 351 ERROR XXX openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/module/module.py", line 534, in button_immediate_upgrade
    return self._button_immediate_function(cr, uid, ids, self.button_upgrade, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/sources/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 350, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 759, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/additional_addons/connector/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/models.py", line 4123, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/sources/odoo/openerp/models.py", line 4267, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/sources/odoo/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "business_requirement_category_pkey"
DETAIL:  Key (id)=(55) already exists.
" while parsing /opt/odoo/additional_addons/business-requirement/business_requirement/data/business_requirement_demo.xml:10, near
<record id="business_requirement_category_2" model="business.requirement.category">
            <field name="name">ERP</field>
        </record>
````

````
2017-09-12 08:03:47,740 350 ERROR XXX werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/service/server.py", line 294, in app
    return self.app(e, s)
  File "/opt/odoo/sources/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1299, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/sources/odoo/openerp/http.py", line 1444, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/odoo/sources/odoo/openerp/http.py", line 355, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/odoo/sources/odoo/openerp/modules/registry.py", line 339, in get
    update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 350, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/odoo/sources/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 751, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 828, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/sources/odoo/openerp/tools/convert.py", line 839, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/ir/ir_model.py", line 909, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup

  File "/opt/odoo/sources/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/sources/odoo/openerp/addons/base/ir/ir_model.py", line 899, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base.res_partner_2" while parsing /opt/odoo/additional_addons/business-requirement/business_requirement/data/business_requirement_demo.xml:23, near
<record id="project_website" model="project.project">
            <field name="name">Corporate Website</field>
            <field name="partner_id" ref="base.res_partner_2"/>
        </record>
````

**Review by martintorresvm — APPROVED** [review]
Quite big PR. But seems only move files and add the forcecreate="0"

**Comment by seb-elico** [comment]
Found the root cause. The BR modules had the flag `demo` to `True`. Probably due to a bug in a very early version of BR modules. Sorry for the noise.

**Pull request closed without merging**
