### PR TITLE
[FIX][8.0-i194-BR001030-T22335] create project a chatter notification should be added to the BR

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
@elicoidal @seb-elico @victormartinelicocorp 
improved chatter notification with BR project name.
#194 
please review code.

### CODE REVIEW

**Comment by elicoidal** [comment]
:-1: 
the chatter is created in the project thread,  not in the BR object thread.
@sudhir-serpentcs 
Requirement is that in the BR Object a notification is posted when the project is created. Let me know if unclear

**Comment by sudhir-serpentcs** [comment]
@elicoidal 
Please review code.

**Review by elicoidal — APPROVED** [review]
LGTM

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb-elico

**Review by martintorresvm — APPROVED** [review]

**Comment by elicoidal** [comment]
Fast tracking as trivial

**Pull request merged**
