### PR TITLE
[FIX] [8.0] [i176] BR print report is not printing RL if not related to an DL

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
@elicoidal @seb-elico @victormartinelicocorp
Fixed the issue to print other resources.

### CODE REVIEW

**Comment by elicoidal** [comment]
@sudhir-serpentcs Functional tests are failing on my end: please check the runbot for the example.
Current output for the report is the same as standard resource report.

**Comment by sudhir-serpentcs** [comment]
@elicoidal I checked the runbot, but all the resources had deliverable reference.

Other resources are resources with empty reference of deliverable. I tested on runbot and it worked for me can you please check again. I guess it will work now.

**Comment by serpentcs-dev1** [comment]
@elicoidal it displays at the end of the report under 'Other Resources' title.

**Comment by elicoidal** [comment]
> Other resources are resources with empty reference of deliverable. I tested on runbot and it worked for me can you please check again. I guess it will work now.

:man_facepalming: of course!

LGTM

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@victormartinelicocorp @seb-elico

**Review by martintorresvm — APPROVED** [review]

**Comment by serpentcs-dev1** [comment]
For reference : This PR fixes Issue https://github.com/OCA/business-requirement/issues/176

**Pull request merged**
