### PR TITLE
[IMP] [8.0-i190-BR001028-T22318] Added sequence field and handler opt…

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
This PR refers to Issue #190 
@elicoidal @victormartinelicocorp Please review.

### CODE REVIEW

**Comment by elicoidal** [comment]
@sudhir-serpentcs 
When inserting the deliverable with template in the BR, the order should be the one defined in the deliverable product: 
screenshot from 2017-07-17 20-12-15
screenshot from 2017-07-17 20-11-30

 I expect: 3, 1, 2 when inserting the deliverable in the BR.
Let me know if unclear

**Comment by sudhir-serpentcs** [comment]
@elicoidal @victormartinelicocorp @seb-elico Modified the code so that we will have the RLs in the sequence they were added in template.
Please review the code.

**Comment by elicoidal** [comment]
@sudhir-serpentcs 
I followed:
1. add deliv product in delivery.
2. drag and drop in the delivery form
3. save the delivery
4. my sort order is not saved in the form
Expected: my sort order is save in DL

**Comment by sudhir-serpentcs** [comment]
@elicoidal Sorry I didn't get your point.
It would be more helpful if you can explain it in more detail or discuss it on skype group.

**Comment by sudhir-serpentcs** [comment]
@elicoidal Fixed the code / added _order = sequence to sort the RLs in sequence order.
Please test it.

**Comment by elicoidal** [comment]
@sudhir-serpentcs 
When changing the sorting with drag and drop in DL: works fine now
Nevertheless, 
1. I created a Deliverable product (3, 1, 2)
2. Added to a DL
3. The sorting is displayed 3 2 1 but when saving displayed 3 1 2

**Comment by sudhir-serpentcs** [comment]
@elicoidal I uninstall the **business_requirement_deliverable_default** module (I think we are not going to use this module anymore) from the runbot and then tried it and it worked for me. Please go and test it again and let me know whether it worked for you.
CC: @victormartinelicocorp

**Comment by elicoidal** [comment]
@sudhir-serpentcs please create a PR to remove business_requirement_deliverable_default from the repository.
It is now indeed duplicated and more annoying than useful

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@victormartinelicocorp

**Review by martintorresvm — APPROVED** [review]

**Comment by sudhir-serpentcs** [comment]
> @sudhir-serpentcs please create a PR to remove business_requirement_deliverable_default from the repository.
It is now indeed duplicated and more annoying than useful

@elicoidal  Sure I will do quickly.
CC: @victormartinelicocorp

**Comment by sudhir-serpentcs** [comment]
Removed the business_requirement_deliverable_default module in PR #221 (Merged).

**Pull request merged**
